### ISSUE TITLE
Camera glitching while walking

### ISSUE THREAD

**Issue by EnolCook** [ElmarTalibzade/OpenPlayerController#1]
When using the Example map, just moving the Player arround on the map make the camera glitch.
The camera go up and down even when not moving the mouse at a regular interval.

Example of the issue:
[GIF](http://i.imgur.com/u901zOt.gif)

**Comment by ElmarTalibzade** [comment]
What Unity version are you using? Did you do any changes to player?

**Comment by EnolCook** [comment]
I'm using 5.4.1f1, nothing changed, just the Project from Github.

**Comment by ElmarTalibzade** [comment]
The issue has been fixed. The project has been upgraded to Unity 2017.1
